from enum import StrEnum
from typing import Literal


class V1_21(StrEnum):
    """v1.21のマインクラフトIDの列挙型です。"""

    # A
    ACACIA_BOAT = "minecraft:acacia_boat"
    ACACIA_BUTTON = "minecraft:acacia_button"
    ACACIA_CHEST_BOAT = "minecraft:acacia_chest_boat"
    ACACIA_DOOR = "minecraft:acacia_door"
    ACACIA_FENCE = "minecraft:acacia_fence"
    ACACIA_FENCE_GATE = "minecraft:acacia_fence_gate"
    ACACIA_HANGING_SIGN = "minecraft:acacia_hanging_sign"
    ACACIA_LEAVES = "minecraft:acacia_leaves"
    ACACIA_LOG = "minecraft:acacia_log"
    ACACIA_PLANKS = "minecraft:acacia_planks"
    ACACIA_PRESSURE_PLATE = "minecraft:acacia_pressure_plate"
    ACACIA_SAPLING = "minecraft:acacia_sapling"
    ACACIA_SIGN = "minecraft:acacia_sign"
    ACACIA_SLAB = "minecraft:acacia_slab"
    ACACIA_STAIRS = "minecraft:acacia_stairs"
    ACACIA_TRAPDOOR = "minecraft:acacia_trapdoor"
    ACACIA_WOOD = "minecraft:acacia_wood"
    ACTIVATOR_RAIL = "minecraft:activator_rail"
    AIR = "minecraft:air"
    ALLAY_SPAWN_EGG = "minecraft:allay_spawn_egg"
    ALLIUM = "minecraft:allium"
    AMETHYST_BLOCK = "minecraft:amethyst_block"
    AMETHYST_CLUSTER = "minecraft:amethyst_cluster"
    AMETHYST_SHARD = "minecraft:amethyst_shard"
    ANCIENT_DEBRIS = "minecraft:ancient_debris"
    ANDESITE = "minecraft:andesite"
    ANDESITE_SLAB = "minecraft:andesite_slab"
    ANDESITE_STAIRS = "minecraft:andesite_stairs"
    ANDESITE_WALL = "minecraft:andesite_wall"
    ANGLER_POTTERY_SHARD = "minecraft:angler_pottery_shard"
    ANVIL = "minecraft:anvil"
    APPLE = "minecraft:apple"
    ARCHER_POTTERY_SHARD = "minecraft:archer_pottery_shard"
    ARMADILLO_SCUTE = "minecraft:armadillo_scute"
    ARMADILLO_SPAWN_EGG = "minecraft:armadillo_spawn_egg"
    ARMOR_STAND = "minecraft:armor_stand"
    ARMS_UP_POTTERY_SHARD = "minecraft:arms_up_pottery_shard"
    ARROW = "minecraft:arrow"
    AXOLOTL_BUCKET = "minecraft:axolotl_bucket"
    AXOLOTL_SPAWN_EGG = "minecraft:axolotl_spawn_egg"
    AZALEA = "minecraft:azalea"
    AZALEA_LEAVES = "minecraft:azalea_leaves"
    AZURE_BLUET = "minecraft:azure_bluet"

    # B
    BAKED_POTATO = "minecraft:baked_potato"
    BAMBOO = "minecraft:bamboo"
    BAMBOO_BLOCK = "minecraft:bamboo_block"
    BAMBOO_BUTTON = "minecraft:bamboo_button"
    BAMBOO_CHEST_RAFT = "minecraft:bamboo_chest_raft"
    BAMBOO_DOOR = "minecraft:bamboo_door"
    BAMBOO_FENCE = "minecraft:bamboo_fence"
    BAMBOO_FENCE_GATE = "minecraft:bamboo_fence_gate"
    BAMBOO_HANGING_SIGN = "minecraft:bamboo_hanging_sign"
    BAMBOO_MOSAIC = "minecraft:bamboo_mosaic"
    BAMBOO_MOSAIC_SLAB = "minecraft:bamboo_mosaic_slab"
    BAMBOO_MOSAIC_STAIRS = "minecraft:bamboo_mosaic_stairs"
    BAMBOO_PLANKS = "minecraft:bamboo_planks"
    BAMBOO_PRESSURE_PLATE = "minecraft:bamboo_pressure_plate"
    BAMBOO_RAFT = "minecraft:bamboo_raft"
    BAMBOO_SIGN = "minecraft:bamboo_sign"
    BAMBOO_SLAB = "minecraft:bamboo_slab"
    BAMBOO_STAIRS = "minecraft:bamboo_stairs"
    BAMBOO_TRAPDOOR = "minecraft:bamboo_trapdoor"
    BARREL = "minecraft:barrel"
    BARRIER = "minecraft:barrier"
    BASALT = "minecraft:basalt"
    BAT_SPAWN_EGG = "minecraft:bat_spawn_egg"
    BEACON = "minecraft:beacon"
    BEDROCK = "minecraft:bedrock"
    BEE_NEST = "minecraft:bee_nest"
    BEE_SPAWN_EGG = "minecraft:bee_spawn_egg"
    BEEF = "minecraft:beef"
    BEEHIVE = "minecraft:beehive"
    BEETROOT = "minecraft:beetroot"
    BEETROOT_SEEDS = "minecraft:beetroot_seeds"
    BEETROOT_SOUP = "minecraft:beetroot_soup"
    BELL = "minecraft:bell"
    BIG_DRIPLEAF = "minecraft:big_dripleaf"
    BIRCH_BOAT = "minecraft:birch_boat"
    BIRCH_BUTTON = "minecraft:birch_button"
    BIRCH_CHEST_BOAT = "minecraft:birch_chest_boat"
    BIRCH_DOOR = "minecraft:birch_door"
    BIRCH_FENCE = "minecraft:birch_fence"
    BIRCH_FENCE_GATE = "minecraft:birch_fence_gate"
    BIRCH_HANGING_SIGN = "minecraft:birch_hanging_sign"
    BIRCH_LEAVES = "minecraft:birch_leaves"
    BIRCH_LOG = "minecraft:birch_log"
    BIRCH_PLANKS = "minecraft:birch_planks"
    BIRCH_PRESSURE_PLATE = "minecraft:birch_pressure_plate"
    BIRCH_SAPLING = "minecraft:birch_sapling"
    BIRCH_SIGN = "minecraft:birch_sign"
    BIRCH_SLAB = "minecraft:birch_slab"
    BIRCH_STAIRS = "minecraft:birch_stairs"
    BIRCH_TRAPDOOR = "minecraft:birch_trapdoor"
    BIRCH_WOOD = "minecraft:birch_wood"
    BLACK_BANNER = "minecraft:black_banner"
    BLACK_BED = "minecraft:black_bed"
    BLACK_CANDLE = "minecraft:black_candle"
    BLACK_CARPET = "minecraft:black_carpet"
    BLACK_CONCRETE = "minecraft:black_concrete"
    BLACK_CONCRETE_POWDER = "minecraft:black_concrete_powder"
    BLACK_DYE = "minecraft:black_dye"
    BLACK_GLAZED_TERRACOTTA = "minecraft:black_glazed_terracotta"
    BLACK_SHULKER_BOX = "minecraft:black_shulker_box"
    BLACK_STAINED_GLASS = "minecraft:black_stained_glass"
    BLACK_STAINED_GLASS_PANE = "minecraft:black_stained_glass_pane"
    BLACK_TERRACOTTA = "minecraft:black_terracotta"
    BLACK_WOOL = "minecraft:black_wool"
    BLACKSTONE = "minecraft:blackstone"
    BLACKSTONE_SLAB = "minecraft:blackstone_slab"
    BLACKSTONE_STAIRS = "minecraft:blackstone_stairs"
    BLACKSTONE_WALL = "minecraft:blackstone_wall"
    BLADE_POTTERTY_SHARD = "minecraft:blade_pottery_shard"
    BLAST_FURNACE = "minecraft:blast_furnace"
    BLAZE_POWDER = "minecraft:blaze_powder"
    BLAZE_ROD = "minecraft:blaze_rod"
    BLAZE_SPAWN_EGG = "minecraft:blaze_spawn_egg"
    BLUE_BANNER = "minecraft:blue_banner"
    BLUE_BED = "minecraft:blue_bed"
    BLUE_CANDLE = "minecraft:blue_candle"
    BLUE_CARPET = "minecraft:blue_carpet"
    BLUE_CONCRETE = "minecraft:blue_concrete"
    BLUE_CONCRETE_POWDER = "minecraft:blue_concrete_powder"
    BLUE_DYE = "minecraft:blue_dye"
    BLUE_GLAZED_TERRACOTTA = "minecraft:blue_glazed_terracotta"
    BLUE_ICE = "minecraft:blue_ice"
    BLUE_ORCHID = "minecraft:blue_orchid"
    BLUE_SHULKER_BOX = "minecraft:blue_shulker_box"
    BLUE_STAINED_GLASS = "minecraft:blue_stained_glass"
    BLUE_STAINED_GLASS_PANE = "minecraft:blue_stained_glass_pane"
    BLUE_TERRACOTTA = "minecraft:blue_terracotta"
    BLUE_WOOL = "minecraft:blue_wool"
    BOGGED_SPAWN_EGG = "minecraft:bogged_spawn_egg"
    BOLT_ARMOR_TRIM_SMITHING_TEMPLATE = "minecraft:bolt_armor_trim_smithing_template"
    BONE = "minecraft:bone"
    BONE_BLOCK = "minecraft:bone_block"
    BONE_MEAL = "minecraft:bone_meal"
    BOOK = "minecraft:book"
    BOOKSHELF = "minecraft:bookshelf"
    BOW = "minecraft:bow"
    BOWL = "minecraft:bowl"
    BRAIN_CORAL = "minecraft:brain_coral"
    BRAIN_CORAL_BLOCK = "minecraft:brain_coral_block"
    BRAIN_CORAL_FAN = "minecraft:brain_coral_fan"
    BREAD = "minecraft:bread"
    BREEZE_ROD = "minecraft:breeze_rod"
    BREEZE_SPAWN_EGG = "minecraft:breeze_spawn_egg"
    BREWER_POTTERY_SHARD = "minecraft:brewer_pottery_shard"
    BREWING_STAND = "minecraft:brewing_stand"
    BRICK = "minecraft:brick"
    BRICK_SLAB = "minecraft:brick_slab"
    BRICK_STAIRS = "minecraft:brick_stairs"
    BRICK_WALL = "minecraft:brick_wall"
    BRICKS = "minecraft:bricks"
    BROWN_BANNER = "minecraft:brown_banner"
    BROWN_BED = "minecraft:brown_bed"
    BROWN_CANDLE = "minecraft:brown_candle"
    BROWN_CARPET = "minecraft:brown_carpet"
    BROWN_CONCRETE = "minecraft:brown_concrete"
    BROWN_CONCRETE_POWDER = "minecraft:brown_concrete_powder"
    BROWN_DYE = "minecraft:brown_dye"
    BROWN_GLAZED_TERRACOTTA = "minecraft:brown_glazed_terracotta"
    BROWN_MUSHROOM = "minecraft:brown_mushroom"
    BROWN_MUSHROOM_BLOCK = "minecraft:brown_mushroom_block"
    BROWN_SHULKER_BOX = "minecraft:brown_shulker_box"
    BROWN_STAINED_GLASS = "minecraft:brown_stained_glass"
    BROWN_STAINED_GLASS_PANE = "minecraft:brown_stained_glass_pane"
    BROWN_TERRACOTTA = "minecraft:brown_terracotta"
    BROWN_WOOL = "minecraft:brown_wool"
    BRUSH = "minecraft:brush"
    BUBBLE_CORAL = "minecraft:bubble_coral"
    BUBBLE_CORAL_BLOCK = "minecraft:bubble_coral_block"
    BUBBLE_CORAL_FAN = "minecraft:bubble_coral_fan"
    BUCKET = "minecraft:bucket"
    BUDDING_AMETHYST = "minecraft:budding_amethyst"
    BUNDLE = "minecraft:bundle"
    BURN_POTTERY_SHARD = "minecraft:burn_pottery_shard"


MinecraftVersion = Literal["1.21"]


def GET_MCID(MinecraftVersion: MinecraftVersion):
    """マインクラフトIDの列挙型を取得します。

    対応バージョン:
        - 1.21
    """

    if MinecraftVersion == "1.21":
        return V1_21
    else:
        raise ValueError("バージョン非対応です。")
